# name: build Angular App

# on: 
#   push:
#     branches: [ main ]

# jobs:
#   build: 
#     runs-on: ubuntu-latest
#     steps:
#       - name: a
#         run: ls
name: Angular GitHub CI/CD
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Publish
        uses: selenehyun/gh-push@master
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_ACCESS_TOKEN }}
          COMMIT_FILES: docs/*
          REPO_FULLNAME: Txuan2000/game-three.github.io
          BRANCH: deploy
#       - uses: lcdsmao/update-branch@v3
#         with:
#           # Or use personal access token
#           token: ${{ secrets.GITHUB_TOKEN }}
#           # One of MERGE, SQUASH, REBASE (default: MERGE)
#           autoMergeMethod: SQUASH
#           # Ignore pull requests without these labels
#           requiredLabels: auto-merge
#           # Required at least 2 approves (default: 0)
#           requiredApprovals: 2
#           # Required approvals from all requested reviewers
#           allRequestedReviewersMustApprove: true
#           # Required these status checks success
#           requiredStatusChecks: |
#             build_pr
#             WIP
